// src/law/registry_cache.c
#include "yai_cli/law/law_registry_cache.h"

#include <string.h>

// -------------------------------------------------------------------
// IMPORTANT:
//
// This file is meant to be AUTO-GENERATED by:
//   tools/python/yai_cli_tools/gen/gen_stubs.py
//
// Until generated, we keep a safe empty cache so the CLI still builds.
// -------------------------------------------------------------------

static const yai_law_registry_t g_empty = {
  .version = "0",
  .binary = "yai",
  .commands = NULL,
  .commands_len = 0,
  .artifacts = NULL,
  .artifacts_len = 0,
};

const yai_law_registry_t* yai_law_registry_cache(void) {
  return &g_empty;
}

const yai_law_command_t* yai_law_registry_find_command(const char* id) {
  if (!id) return NULL;
  const yai_law_registry_t* r = yai_law_registry_cache();
  for (size_t i = 0; i < r->commands_len; i++) {
    const yai_law_command_t* c = &r->commands[i];
    if (c->id && strcmp(c->id, id) == 0) return c;
  }
  return NULL;
}

const yai_law_artifact_role_t* yai_law_registry_find_artifact_role(const char* role) {
  if (!role) return NULL;
  const yai_law_registry_t* r = yai_law_registry_cache();
  for (size_t i = 0; i < r->artifacts_len; i++) {
    const yai_law_artifact_role_t* a = &r->artifacts[i];
    if (a->role && strcmp(a->role, role) == 0) return a;
  }
  return NULL;
}

int yai_law_registry_cache_validate(void) {
  const yai_law_registry_t* r = yai_law_registry_cache();

  // Unique command IDs
  for (size_t i = 0; i < r->commands_len; i++) {
    const yai_law_command_t* a = &r->commands[i];
    if (!a->id || !a->name || !a->group || !a->summary) return 1;

    for (size_t j = i + 1; j < r->commands_len; j++) {
      const yai_law_command_t* b = &r->commands[j];
      if (b->id && strcmp(a->id, b->id) == 0) return 2;
    }
  }

  // Artifact roles must have schema_ref + description
  for (size_t i = 0; i < r->artifacts_len; i++) {
    const yai_law_artifact_role_t* a = &r->artifacts[i];
    if (!a->role || !a->schema_ref || !a->description) return 3;
  }

  return 0;
}